Feat: Update patch useroperation to return optional gas limit values
MetaMask/keyring-api pull request #250
Opened 2024-02-16 10:37 UTC by montelaidev

This PR update the docs and adds new optional return values during the PatchUserOperation.Set

* Fixes #260 [https://app.zenhub.com/workspaces/metamask-accounts-team-v2-64c91cbeaa9d1c00126621fd/issues/gh/metamask/accounts-planning/260]

2024-02-17 00:37 UTC, gantunesr commented on docs/evm_methods_userOp.md
> +    - `preverificationGas` (optional)
```suggestion
    - `preVerificationGas` (optional)
```

2024-02-19 10:11 UTC, danroc requested changes

2024-02-19 10:11 UTC, danroc commented on src/eth/erc4337/types.ts
> +import { optional, string, type Infer } from 'superstruct';
You should use `exactOptional` from `../../superstruct` instead of `optional` to correctly handle the `exactOptionalPropertyTypes` compiler flag.

2024-02-19 10:11 UTC, danroc commented on src/eth/erc4337/types.ts
> +  callDataLimit: optional(EthUint256Struct),
Should be `callGasLimit`

2024-02-19 10:11 UTC, danroc commented on docs/evm_methods_userOp.md
> +      - Pattern: `^0x[0-9a-f]*$`
The pattern used for `uint256` values is `^0x([1-9a-f][0-9a-f]*|0)$`

2024-02-19 10:11 UTC, danroc commented on docs/evm_methods_userOp.md
> +      - Pattern: `^0x[0-9a-f]*$`
The pattern used for `uint256` values is `^0x([1-9a-f][0-9a-f]*|0)$`

2024-02-19 10:11 UTC, danroc commented on docs/evm_methods_userOp.md
> +      - Pattern: `^0x[0-9a-f]*$`
The pattern used for `uint256` values is `^0x([1-9a-f][0-9a-f]*|0)$`

2024-02-20 13:24 UTC, danroc approved these changes
LGTM

2024-02-20 14:49 UTC, merged